name: "deploy"
version: "0.1.0"
description: "deploy chart with the possibility to skip dependencies"
command: "$HELM_PLUGIN_DIR/bin/helmdeploy"
downloaders:
- command: "bin/helmdeploy"
useTunnel: false
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
